Update beef.md
yuri-von-gella/awesome-michelin pull request #2
Opened 2021-01-05 11:43 UTC by parkgunuk

고기 맛집 추가

2021-01-05 19:15 UTC, adamdoha approved these changes
숲으로 서울 방방곡곡 다 가보셨네;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
추천 감사합니다

2021-01-05 19:15 UTC, adamdoha commented on md/beef.md
> +> 특징 : 미쉐린 빕구르밍에 선정
Good recommend!!!!!

2021-01-05 19:15 UTC, adamdoha commented on md/beef.md
> +> 특징 : 육회를 겉을 구워준다, 마지막에 먹는 크림볶음밥 꿀맛
육회 겉을 구워주다니 ㄷㄷ

2021-01-06 00:43 UTC, Dinoryong commented on md/beef.md
> +> 특징 : 육회를 겉을 구워준다, 마지막에 먹는 크림볶음밥 꿀맛
타다끼!댑악

2021-01-06 00:52 UTC, Dinoryong commented on md/beef.md
> +> 특징 : 미쉐린 빕구르밍에 선정
크으으!

2021-01-06 02:00 UTC, 738 commented on md/beef.md
> +> 특징 : 미쉐린 빕구르밍에 선정
`빕구르밍` -> `빕 구르망`

수정 요청드립니다.

2021-01-06 02:18 UTC, adamdoha requested changes

2021-01-06 02:18 UTC, adamdoha commented on md/beef.md
> +> 특징 : 미쉐린 빕구르밍에 선정
준우님 리뷰 감사합니다. 
@parkgunuk 의견 반영 부탁드립니다.

2021-01-06 04:53 UTC, adamdoha approved these changes
감사합니다.

2021-01-06 07:26 UTC, Dinoryong approved these changes

2021-01-06 07:26 UTC, Dinoryong commented on md/beef.md
> +## [십원집] (https://map.naver.com/v5/entry/place/13587483?c=14134890.861225236,4517938.807739029,15,0,0,0,dh&placePath=%3Fentry=plt)
이름이 독특

2021-01-06 07:28 UTC, merged